dist: trusty
language: cpp
os: linux
sudo: required
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - gcc-7

before_install:
  - sudo apt-get install librdmacm-dev
  - sudo apt-get install libibverbs-dev
  - export CC=gcc-7
  - export CXX=g++-7
  
install:
  - chmod +x scripts/prerequisites/*.sh
  - sudo -E scripts/prerequisites/install-libfabric.sh
  - sudo -E scripts/prerequisites/install-spdlog.sh
  - sudo -E scripts/prerequisites/install-mutils.sh
  - sudo -E scripts/prerequisites/install-mutils-containers.sh
  - sudo -E scripts/prerequisites/install-mutils-tasks.sh

before_script:
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - if [ -n "$CLANG_VERSION" ]; then export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"; fi
  - which $CXX
  - which $CC
  - $CXX --version
  - cmake --version

script:
  - mkdir Release
  - cd Release
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j `lscpu | grep "^CPU(" | awk '{print $2}'`
  - make install
