dist: trusty
language: cpp
os: linux
sudo: required

before_install:
  - ifconfig
  - sudo apt-get install librdmacm-dev
  - sudo apt-get install libibverbs-dev
  - export CC=$useCC
  - export CXX=$useCXX
  - which $CXX
  - which $CC
  - $CXX --version
  - cmake --version
  
install:
  - chmod +x scripts/prerequisites/*.sh
  - sudo env "PATH=$PATH" scripts/prerequisites/install-libfabric.sh
  - sudo env "PATH=$PATH" scripts/prerequisites/install-spdlog.sh
  - sudo env "PATH=$PATH" scripts/prerequisites/install-mutils.sh
  - sudo env "PATH=$PATH" scripts/prerequisites/install-mutils-containers.sh
  - sudo env "PATH=$PATH" scripts/prerequisites/install-mutils-tasks.sh

matrix:
  include:
    # build with gcc7 on Release/Debug
    - env: BUILD_TYPE=Release useCC=gcc-7 useCXX=g++-7
      addons: &gcc7
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gcc-7
    - env: BUILD_TYPE=Debug useCC=gcc-7 useCXX=g++-7
      addons: *gcc7
      
    # build with clang7 on Release/Debug
    - env: BUILD_TYPE=Release CC=clang-7.0 CXX=clang++-7.0
      addons: &clang7
        apt:
          sources:
            - llvm-toolchain-trusty-7
            - ubuntu-toolchain-r-test
          packages:
            - clang-7
    - env: BUILD_TYPE=Debug CC=clang-7.0 CXX=clang++-7.0
      addons: *clang7

script:
# build Derecho
  - mkdir $BUILD_TYPE
  - cd $BUILD_TYPE
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - make -j `lscpu | grep "^CPU(" | awk '{print $2}'`
  - sudo make install
  
# prepare config files for testing
  - wget https://raw.githubusercontent.com/xinzheyang/derecho-unified/travis/derecho0.cfg -P ~
  - wget https://raw.githubusercontent.com/xinzheyang/derecho-unified/travis/derecho1.cfg -P ~
  
# performance tests
  - cd src/applications/tests/performance_tests/
  - DERECHO_CONF_FILE=~/derecho0.cfg ./bandwidth_test 2 2 1000 0 & DERECHO_CONF_FILE=~/derecho1.cfg ./bandwidth_test 2 2 1000 0
  - cat data_derecho_bw
  
# unit tests
  - cd ../unit_tests/
  - DERECHO_CONF_FILE=~/derecho0.cfg ./cooked_send_test 2 & DERECHO_CONF_FILE=~/derecho1.cfg ./cooked_send_test 2
#  - DERECHO_CONF_FILE=~/derecho0.cfg ./delivery_order_test ~/derecho0.cfg 2 1000 10240 & DERECHO_CONF_FILE=~/derecho1.cfg ./delivery_order_test ~/derecho1.cfg 2 1000 10240
  - DERECHO_CONF_FILE=~/derecho0.cfg ./subgroup_function_tester
